apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-microservice-app
  labels:
    app: ml-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : ml-microservice-app
  template:
    metadata:
      labels:
        app: ml-microservice-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ml-microservice-app
        image: souravcoder99/mlapi:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name:  ml-microservice-svc
spec:
  selector:
    app:  ml-microservice-app
  ports:
  - port:  8080
    targetPort:  8080